### ISSUE TITLE
Crash/error on load

### ISSUE THREAD

**Issue by jamesweech** [kraftwerk28/spigot-tg-bridge#2]
Hey there, I'm having the following issues upon load, Looking at it I think you're built for Java10 when the spigot build I am on requires/requests 8? If this is the case no worries it's my bad for a plugin requiring such a old version of java and I'll close the issue :) 

```
[20:02:09] [Server thread/INFO]: [SpigotTGBridge] Enabling SpigotTGBridge v0.0.4
[20:02:09] [Server thread/ERROR]: Error occurred while enabling SpigotTGBridge v0.0.4 (Is it up to date?)
java.lang.NoSuchMethodError: guava10.com.google.common.cache.CacheBuilder.build()Lguava10/com/google/common/cache/Cache;
        at com.google.inject.internal.WeakKeySet.<init>(WeakKeySet.java:66) ~[?:?]
        at com.google.inject.internal.InheritingState.<init>(InheritingState.java:63) ~[?:?]
        at com.google.inject.internal.InjectorShell$Builder.getState(InjectorShell.java:208) ~[?:?]
        at com.google.inject.internal.InjectorShell$Builder.lock(InjectorShell.java:114) ~[?:?]
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:102) ~[?:?]
        at com.google.inject.Guice.createInjector(Guice.java:87) ~[?:?]
        at com.google.inject.Guice.createInjector(Guice.java:69) ~[?:?]
        at com.google.inject.Guice.createInjector(Guice.java:59) ~[?:?]
        at org.telegram.telegrambots.meta.ApiContext.getInjector(ApiContext.java:48) ~[?:?]
        at org.telegram.telegrambots.meta.ApiContext.getInstance(ApiContext.java:27) ~[?:?]
        at org.telegram.telegrambots.bots.TelegramLongPollingBot.<init>(TelegramLongPollingBot.java:16) ~[?:?]
        at org.kraftwerk28.spigot_tg_bridge.Bot.<init>(Bot.kt:12) ~[?:?]
        at org.kraftwerk28.spigot_tg_bridge.Plugin.onEnable(Plugin.kt:32) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.58]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.58]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.58]
        at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:463) [ayq.class:?]
        at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138) [ayq.class:?]
        at net.minecraft.world.World.<init>(World.java:374) [ahb.class:?]
        at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

**Comment by kraftwerk28** [comment]
Hi, excuse me for late response, about a half of month ago I was busy cause had to complete my exams :sweat_smile:. I was able to build this plugin under java version 1.8 and didn't run into a problem. Now, I do build it on my archlinux machine with java 14.0.1 and it also succeeds. I advice you to close this repo and try to run `./gradlew shadowJar` (or `gradlew.bat shadowJar` on Windows). This should build plugin from scratch, being compatible with your Java version. I'll make release .jar on GitHub up to date ASAP

**Comment by jamesweech** [comment]
Thanks for looking at it at all and I hope the exams went well! 

Will compile asap, many thanks :)
