### ISSUE TITLE
It works well except I get loads of errors…

### ISSUE THREAD

**Issue by SabreT00th84** [kraftwerk28/spigot-tg-bridge#28]
I installed spigot-to-bridge on a 1.18.2 paper/spigot server and followed made the telegram bot. I sent a message in the telegram group and it forwarded to the game chat but it also generated a huge error:

`[ERROR] .... Thread DefaultDispatcher-worker-2 failed main thread check: ChunkHolder update
java.lang.Throwable: null
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.18.2.jar:git-Paper-247]
at net.minecraft.server.level.ChunkHolder.addToBroadcastMap(ChunkHolder.java:322) ~[?:?]
at net.minecraft.server.level.ChunkHolder.blockChanged(ChunkHolder.java:282) ~[?:?]
at net.minecraft.server.level.ServerChunkCache.blockChanged(ServerChunkCache.java:1129) ~[?:?]
at net.minecraft.server.level.ServerLevel.sendBlockUpdated(ServerLevel.java:1557) ~[?:?]
at net.minecraft.world.level.block.entity.CommandBlockEntity$1.onUpdated(CommandBlockEntity.java:45) ~[?:?]
at net.minecraft.world.level.BaseCommandBlock.sendMessage(BaseCommandBlock.java:180) ~[?:?]
at org.bukkit.craftbukkit.v1_18_R2.command.CraftBlockCommandSender.sendMessage(CraftBlockCommandSender.java:33) ~[paper-1.18.2.jar:git-Paper-247]
at org.bukkit.command.CommandSender.sendMessage(CommandSender.java:128) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:254) ~[adventure-api-4.10.1.jar:?]
at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:228) ~[adventure-api-4.10.1.jar:?]
at org.bukkit.craftbukkit.v1_18_R2.CraftServer.broadcast(CraftServer.java:1760) ~[paper-1.18.2.jar:git-Paper-247]
at org.bukkit.craftbukkit.v1_18_R2.CraftServer.broadcast(CraftServer.java:1732) ~[paper-1.18.2.jar:git-Paper-247]
at org.bukkit.craftbukkit.v1_18_R2.CraftServer.broadcastMessage(CraftServer.java:641) ~[paper-1.18.2.jar:git-Paper-247]
at org.kraftwerk28.spigot_tg_bridge.Plugin.sendMessageToMinecraft(Plugin.kt:84) ~[spigot-tg-bridge-1.15-v0.20.jar:?]
at org.kraftwerk28.spigot_tg_bridge.TgBot.onTextHandler(TgBot.kt:247) ~[spigot-tg-bridge-1.15-v0.20.jar:?]
at org.kraftwerk28.spigot_tg_bridge.TgBot.handleUpdate(TgBot.kt:142) ~[spigot-tg-bridge-1.15-v0.20.jar:?]
at org.kraftwerk28.spigot_tg_bridge.TgBot.access$handleUpdate(TgBot.kt:24) ~[spigot-tg-bridge-1.15-v0.20.jar:?]
at org.kraftwerk28.spigot_tg_bridge.TgBot$initHandler$1.invokeSuspend(TgBot.kt:119) ~[spigot-tg-bridge-1.15-v0.20.jar:?]
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[spigot-tg-bridge-1.15-v0.20.jar:?]
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[spigot-tg-bridge-1.15-v0.20.jar:?]
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) ~[spigot-tg-bridge-1.15-v0.20.jar:?]
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[spigot-tg-bridge-1.15-v0.20.jar:?]
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) ~[spigot-tg-bridge-1.15-v0.20.jar:?]
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) ~[spigot-tg-bridge-1.15-v0.20.jar:?]
[WARNING] .... java.lang.IllegalStateException: Asynchronous ChunkHolder update!
[WARNING] .... at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16)
[WARNING] .... at net.minecraft.server.level.PlayerChunk.addToBroadcastMap(PlayerChunk.java:322)
[WARNING] .... at net.minecraft.server.level.PlayerChunk.a(PlayerChunk.java:282)
[WARNING] .... at net.minecraft.server.level.ChunkProviderServer.a(ChunkProviderServer.java:1129)
[WARNING] .... at net.minecraft.server.level.WorldServer.a(WorldServer.java:1557)
[WARNING] .... at net.minecraft.world.level.block.entity.TileEntityCommand$1.f(TileEntityCommand.java:45)
[WARNING] .... at net.minecraft.world.level.CommandBlockListenerAbstract.a(CommandBlockListenerAbstract.java:180)
[WARNING] .... at org.bukkit.craftbukkit.v1_18_R2.command.CraftBlockCommandSender.sendMessage(CraftBlockCommandSender.java:33)
[WARNING] .... at org.bukkit.command.CommandSender.sendMessage(CommandSender.java:128)
[WARNING] .... at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:254)
[WARNING] .... at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:228)
[WARNING] .... at org.bukkit.craftbukkit.v1_18_R2.CraftServer.broadcast(CraftServer.java:1760)
[WARNING] .... at org.bukkit.craftbukkit.v1_18_R2.CraftServer.broadcast(CraftServer.java:1732)
[WARNING] .... at org.bukkit.craftbukkit.v1_18_R2.CraftServer.broadcastMessage(CraftServer.java:641)
[WARNING] .... at spigot-tg-bridge-1.15-v0.20.jar//org.kraftwerk28.spigot_tg_bridge.Plugin.sendMessageToMinecraft(Plugin.kt:84)
[WARNING] .... at spigot-tg-bridge-1.15-v0.20.jar//org.kraftwerk28.spigot_tg_bridge.TgBot.onTextHandler(TgBot.kt:247)
[WARNING] .... at spigot-tg-bridge-1.15-v0.20.jar//org.kraftwerk28.spigot_tg_bridge.TgBot.handleUpdate(TgBot.kt:142)
[WARNING] .... at spigot-tg-bridge-1.15-v0.20.jar//org.kraftwerk28.spigot_tg_bridge.TgBot.access$handleUpdate(TgBot.kt:24)
[WARNING] .... at spigot-tg-bridge-1.15-v0.20.jar//org.kraftwerk28.spigot_tg_bridge.TgBot$initHandler$1.invokeSuspend(TgBot.kt:119)
[WARNING] .... at spigot-tg-bridge-1.15-v0.20.jar//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[WARNING] .... at spigot-tg-bridge-1.15-v0.20.jar//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[WARNING] .... at spigot-tg-bridge-1.15-v0.20.jar//kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[WARNING] .... at spigot-tg-bridge-1.15-v0.20.jar//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[WARNING] .... at spigot-tg-bridge-1.15-v0.20.jar//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[WARNING] .... at spigot-tg-bridge-1.15-v0.20.jar//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)`

I have no idea what this means. Please help.

**Comment by SabreT00th84** [comment]
It works perfectly now, don’t know what the problem was.
